### ISSUE TITLE
https://outlook.office.com/connectors/oam/publish link is broken and throws error page

### ISSUE THREAD

**Issue by srinigeddam** [OfficeDev/outlook-dev-docs#925] opened 2021-05-12 18:52 UTC
trying to register the publisher on actionable messages dev dashboard using the link https://outlook.office.com/connectors/oam/publish
and it throws following error message:

:-(
Something went wrong.
An unexpected error occurred. Please try again.
RequestId: 6232b550-5fca-4066-8f26-310786dec32d
Server: MWHPR21MB0176
Date: 5/12/2021 4:12:45 PM
Fewer details...
 Back to configurations

**Comment by jasonjoh** [comment] 2021-05-13 13:02
Apologies for the inconvenience. This is a know issue at the moment that is actively being addressed. Closing this issue as this is not a documentation issue.

**Closed by jasonjoh** 2021-05-13 13:02 UTC
Labels: Area: actionable messages, Type: product bug

**Comment by Peter-Ross-C** [comment] 2021-05-18 13:27
@jasonjoh  Is there somewhere we can track this issue or get an ETA? (Or do you know what the ETA is on a fix?) Also does it effect already registered connectors or is the issue just around displaying the dashboard?

**Comment by jasonjoh** [comment] 2021-05-18 14:30
I'm sorry but there's no public ticketing system to track this. This does not impact existing connector/senders. I don't have a specific ETA but it is actively being worked on.

**Comment by Peter-Ross-C** [comment] 2021-05-18 14:45
Alright, perfect. Thanks for  your response @jasonjoh. Appreciated.

**Comment by rcappe** [comment] 2021-05-19 07:17
I'm a little worried, it's been 7 days and the problem is still not solved.
Are Actionable Messages a technology that MS believes in?
We are making some investments as a company and this problem does not make us feel comfortable.

**Comment by SiddharthaVinnakote** [comment] 2021-05-20 04:31
Hey @rcappe , I am really sorry for your experience. I want to assure you that this is a big focus area for us. 
We are have a fix for this problem and are actively testing this. We will be deploying the fix this week. It should resolve for you by Friday PST.

**Comment by SiddharthaVinnakote** [comment] 2021-05-22 10:08
Following up on the above message. The fix should be deployed on all machines as of now and the problem should be solved. If it doesn't work the 1st time, I suggest you try after clearing the cookies.
Thanks for your patience.
