### ISSUE TITLE
Receive an error screen when attempting to access the developer dashboard

### ISSUE THREAD

**Issue by Peter-Ross-C** [OfficeDev/outlook-dev-docs#928] opened 2021-05-18 13:01 UTC
Good day,

I'm receiving the following error when opening the [developer dashboard](https://aka.ms/publishoam)

![image](https://user-images.githubusercontent.com/39487410/118655355-c37dda00-b7e9-11eb-9402-2705a5a08fe3.png)

I've tested trying to login with two different tenant accounts and receive the same thing. Is there some sort of service issue going on? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard?source=docs)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment] 2021-05-18 13:23
Duplicate of #925. 

> Apologies for the inconvenience. This is a know issue at the moment that is actively being addressed. Closing this issue as this is not a documentation issue.

**Closed by jasonjoh** 2021-05-18 13:23 UTC
Labels: Needs: triage :mag:

**Comment by Peter-Ross-C** [comment] 2021-05-18 13:26
Cool, thanks @jasonjoh
