### ISSUE TITLE
I'm not able to access developer dashboard to work for Outlook Actionable messages, please advise. Thank you

### ISSUE THREAD

**Issue by yaseralhosani** [OfficeDev/outlook-dev-docs#967] opened 2022-08-19 06:44 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard?source=docs)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment] 2022-08-19 12:38
Duplicate of #964

**Closed by jasonjoh** 2022-08-19 12:38 UTC
Labels: Area: actionable messages, Type: support request
