### ISSUE TITLE
Error opening Actionable Messages Developer Portal

### ISSUE THREAD

**Issue by andrekiba** [OfficeDev/outlook-dev-docs#929] opened 2021-05-18 15:30 UTC
Trying to open https://outlook.office.com/connectors/oam/publish always shows this error:

![image](https://user-images.githubusercontent.com/12699760/118680061-b6b7b100-b7fe-11eb-88db-6cc793d2ff63.png)

I urgently need to register the possibility to send actionable messages for our organization.

**Comment by jasonjoh** [comment] 2021-05-18 15:35
Duplicate of #925. Pinning #925 for awareness though there is no action that can be taken in this repository.

> Apologies for the inconvenience. This is a know issue at the moment that is actively being addressed. Closing this issue as this is not a documentation issue.

**Closed by jasonjoh** 2021-05-18 15:35 UTC
Labels: Needs: triage :mag:
