### ISSUE TITLE
Side loading for outlook desktop is outdated

### ISSUE THREAD

**Issue by Konradox** [OfficeDev/outlook-dev-docs#514] opened 2019-02-05 10:32 UTC
In new outlook, the Get Add-ins button is opening shop website. I can't find any way to upload my own add-in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70e6c303-4a9f-4d68-eb9a-b47d61190a25
* Version Independent ID: 42936d64-c5cd-4999-e348-3a0304f8a6e8
* Content: [Sideload Outlook add-ins for testing - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing#sideload-an-add-in-in-the-new-outlook-on-the-web)
* Content Source: [docs/add-ins/sideload-outlook-add-ins-for-testing.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/sideload-outlook-add-ins-for-testing.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by kbrandl** [comment] 2019-02-05 16:12
@Konradox in the window that opens when you choose the **Get Add-ins** button or **Store** button, do you see the option to choose **ADD-INS** (# 1 in the screenshot below), **My add-ins** (# 2 in the screenshot below), and **Add a custom add-in** (# 3 in the screenshot below)?

![image](https://user-images.githubusercontent.com/3019529/52286768-a5905200-291d-11e9-93fa-9b6f3392a8ba.png)

**Comment by Konradox** [comment] 2019-02-05 16:23
I'm sorry, I thought I've described problem correctly but I did not.
I've got this issue in the desktop version of Outlook. In the web, it's working correctly.
The desktop version won't show me any window like you have posted or like in the docs tutorial. It's always opening this page:
![image](https://user-images.githubusercontent.com/9269007/52287547-a6030a00-296a-11e9-9232-dea13c461723.png)

**Comment by kbrandl** [comment] 2019-02-05 16:38
@Konradox thanks for the clarification. Interestingly, I'm unable to reproduce this issue -- the screenshot I posted in my earlier comment is what I see when I choose the **Get Add-ins** button in Outlook 2016 on Windows (version 1902, build 11362.20000). 

Can you please tell us the specific **version** and **build** of Outlook 2013 and Outlook 2019 in which you're seeing the behavior you've described?

**Comment by Konradox** [comment] 2019-02-05 16:48
Outlook 2019 version 1901 build 11231.20130 (16.0.11231.20122)
Windows build 18323.19h1 - It's an insiders preview version (maybe there is a problem?)

Second PC:
Outlook 2013 version 15.0.5101.1000 (no build information here)
Windows - same build as above

**Comment by kbrandl** [comment] 2019-02-05 16:59
@Konradox thanks for providing this information. 

@exextoc are you able to provide any input on this issue?

**Comment by exextoc** [comment] 2019-02-07 19:22
@Konradox Would you like to share fiddler trace to help us to identify the cause? Thanks

**Comment by siphon** [comment] 2019-03-25 00:08
Any updates on this? I am having exactly the same issue - The "Get Add-ins" button opens up "https://appsource.microsoft.com" and not the window that is shown above. This is using Outlook 16.23 on Mac (build 190309).

**Comment by Konradox** [comment] 2019-03-25 06:54
I found out that there are group policies set up and they blocked my fiddle (I couldn't change proxy server so I couldn't trace packets). If it's possible, I think that policies may block it in my case. I asked a few people in the organisation to check it and the result is the same. For now, I don't need to fix it.

**Comment by simontrain** [comment] 2019-03-29 08:41
Same problem for me. Iin the past I was able to sideload my custom Outlook web add-in to Outlook 2019 desktop. Now I can't. The "Get Add-ins" in button in Outlook now takes me to the https://appsource.microsoft.com/ website. There are no "My Add-ins" so I'm stuck! This seemed to start after I downloaded the latest updates for Office...

**Comment by exextoc** [comment] 2019-03-29 22:34
@simontrain Could please let us know the build number of outlook 2019 desktop and share fiddler trace to identify the issue?

**Comment by celowsky** [comment] 2019-04-05 20:54
I'm having this issue as well in Outlook 2016. Build 16.04266.1003 on Windows 10 Pro

**Comment by delta1186** [comment] 2019-04-10 14:47
So I ran into this same issue today.  In Outlook 2013 I would click File, Manage Add-ins...this opens the owa url in the browser to something like this (on-prem here): 
https://webmail.yourdomain.com/ecp/Extension/InstalledExtensions.slab?rfr=olk&exsvurl=1&realm=yourdomain.com

So when this page loaded I would click on the + button but the only option available to me was "Add from the Office Store"

Add from URL and Add from File were not options.  After reading this article and some others I thought it had to be a permission issue.  Sure enough that was the issue.  My Custom Apps permission was not enabled on the User Role as per the following article:
https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins

On a side note, the Store button on the ribbon in Outlook just goes directly to the store.  No dialog as mentioned.  I am not sure if this behavior will change now that I have enabled this permission.  It is hasn't yet, but only been about 10 minutes since I enabled the role so it might not have propagated to my local client yet.

**Comment by exextoc** [comment] 2019-04-12 07:10
@Konradox @celowsky Are your accounts on-prem or exchange online ?

If it's on-prem, Get-Addins button will open your default browser and load the https://appsource.microsoft.com URL. In order to side-load an add-in, please follow the following instructions.

- Click on File
- Click on Manage Add-ins (last option)
- It will open your default browser where you can see the following
![image](https://user-images.githubusercontent.com/28549921/56018557-138f3600-5d20-11e9-8a96-03c8232c9465.png)
- Click on the + button and you should be able to see the options "Add from file" or "Add from URL"

**Comment by leenorgaard** [comment] 2019-05-13 16:33
I work at a company where my account is on-prem but web mail has been disabled due to security reasons. When I click on File and then click on Manage Add-ins, I get redirected to web mail and then can't do anything from there. Is there another way to test my add-in in my situation?

**Comment by exextoc** [comment] 2019-05-14 04:52
If web mail is blocked, you can try using remote powershell.  The instructions to connect are here https://docs.microsoft.com/en-us/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps and you can use new-app command to install add-in https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/new-app?view=exchange-ps, and remove-app to remove.

**Comment by ElizabethSamuel-MSFT** [comment] 2019-06-04 17:22
It seems like various options have been provided for folks to test their add-ins so I'll close this issue now. If you're still facing some issue with this, let us know and we can reopen this.

Thanks.

**Closed by ElizabethSamuel-MSFT** 2019-06-04 17:22 UTC
Labels: area: add-ins, needs-more-info
