### ISSUE TITLE
Not sure "loadItemProps" ever gets executed

### ISSUE THREAD

**Issue by TobyFish** [OfficeDev/outlook-dev-docs#345] opened 2018-08-17 13:12 UTC
Followed the turotial. Plug in loads and displays table header but table body remoans empty

```
<table class="ms-Table ms-Table--selectable">
            <thead>
               <tr>
                    <th>Property</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody class="prop-table">
        </tbody>
</table>
```

??

**Comment by ElizabethSamuel-MSFT** [comment] 2018-11-09 23:14
@TobyFish: Thanks for trying out our tutorial. Can you confirm which tutorial? It seems like it was one of the quick-starts - https://docs.microsoft.com/outlook/add-ins/quick-start. This info will ensure that we're debugging the correct tutorial with you.

**Comment by kbrandl** [comment] 2018-12-27 00:36
@TobyFish Since I'm unable to reproduce the issue that you've described. I'm going to close this issue. If you're still having this problem, please comment again here in this thread to request that we reopen the issue. And if/when you do that, please also provide the following information in your comment:
* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

**Closed by kbrandl** 2018-12-27 00:36 UTC
Labels: area: add-ins, needs-more-info
