### ISSUE TITLE
Hosting of web server for Outlook add-in

### ISSUE THREAD

**Issue by VikramQH** [OfficeDev/outlook-dev-docs#608] opened 2019-06-04 04:39 UTC
Hello Folks,
To host my outlook add-in, Do I need to deploy it on cloud with public domain? Or I can host it within organization?

-- Vikram

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook task pane add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment] 2019-06-04 16:31
Closing this as a duplicate of issue https://github.com/OfficeDev/outlook-dev-docs/issues/605.

**Closed by ElizabethSamuel-MSFT** 2019-06-04 16:31 UTC
