### ISSUE TITLE
docs/add-ins/web-services.md states that ExpandDL is a supported operation

### ISSUE THREAD

**Issue by duncan-smith-bj** [OfficeDev/outlook-dev-docs#817] opened 2020-01-15 11:29 UTC
docs/add-ins/web-services.md states that ExpandDL is a supported EWS operation. But when I call it from a Mail Add-in in Exchange 2016, Exchange 2019 or Office 365 I get the error:

**_The requested web method is unavailable to this caller or application._**

Is the documentation wrong or is there something I am missing on how to enable this EWS operation for a Mail Add-in?

Cheers
Duncan

**Comment by ElizabethSamuel-MSFT** [comment] 2020-01-21 17:02
@duncan-smith-bj Thanks for raising this issue. We'll investigate.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment] 2020-01-21 18:00
@exextoc Can you advise if the ExpandDL operation is supported?

If it isn't, I'll update the docs accordingly. If it's supposed to be supported, then I'll likely transfer to the office-js repo for further investigation.

Thanks.

**Comment by exextoc** [comment] 2020-01-23 00:03
Per https://github.com/OfficeDev/office-js/issues/937 in the **office-js** repo, this is an issue specifically in Outlook Web. I don't think the documentation needs to be updated at this time, pending the results of that investigation.

Duplicate of https://github.com/OfficeDev/office-js/issues/937

**Closed by exextoc** 2020-01-23 00:03 UTC
Labels: Area: add-ins, Needs: attention :wave:
