### ISSUE TITLE
Cannot access Connector Developer Portal

### ISSUE THREAD

**Issue by serboska** [OfficeDev/outlook-dev-docs#965] opened 2022-08-11 08:00 UTC
On https://docs.microsoft.com/en-us/outlook/actionable-messages/connectors-dev-dashboard there's a link to [Connector Developer Portal](https://aka.ms/connectorsdashboard). However, everytime I go to that URL it gives me the below error (redirection to https://outlook.office.com/connectors/AuthFailure).:
"Something went wrong while authenticating.

Either your session is expired or third party cookies disabled in browser."

I have tried clearing my cookies, signing out and in again, as well as incognito mode. Nothing seems to work.

**Comment by jasonjoh** [comment] 2022-08-11 11:56
Closing as duplicate of #964

**Closed by jasonjoh** 2022-08-11 11:56 UTC
Labels: Needs: triage :mag:
