### ISSUE TITLE
Outlook Developer Dashboard: New actionable message app registration form is broken

### ISSUE THREAD

**Issue by Kamalasekaran** [OfficeDev/outlook-dev-docs#966] opened 2022-08-16 14:04 UTC
Hi Microsoft Support,
Not able to Register service with the actionable email developer dashboard. Tried to Register Emails based on the below article
[Actionable messages via email developer dashboard guide - Outlook Developer | Microsoft Docs](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard)

From the above article, we tried to navigate to https://aka.ms/publishoam or![Uploading ActonableDashboard.png…]() The above links not working it was a return below error. "Something went wrong while authenticating. Either your session is expired or third-party cookies disabled in the browser." Refer to the attached Screen.

**Comment by jasonjoh** [comment] 2022-08-19 12:39
Duplicate of #964

**Closed by jasonjoh** 2022-08-19 12:39 UTC
Labels: Area: actionable messages, Type: support request
